name: build

on:
  push:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.10.7"]
        cabal: [latest]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Set up HLint
        uses: haskell/actions/hlint-setup@v2
        with:
          version: 3.1.6
      - name: Run HLint
        uses: haskell/actions/hlint-run@v2
        with:
          fail-on: warning
      - name: Check for Ormolu formatting
        uses: mrkkrp/ormolu-action@v9
        with:
          pattern: "**/*.hs"
          respect-cabal-files: false
      - name: Update packages list
        run: cabal update
      - name: Build project
        run: cabal build
      - name: Run tests
        run: cabal test --test-show-details=direct --test-options "--color=always"

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
