name: docs

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  docs:
    name: "docs (os: ${{ matrix.os }}, ghc: ${{ matrix.ghc }}, cabal: ${{ matrix.cabal }}, llvm: ${{ matrix.llvm }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ghc: ["9.4.8"]
        cabal: ["3.8"]
        llvm: ["18"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Cache Cabal
        uses: actions/cache@v4
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-docs-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: ${{ runner.os }}-docs-${{ env.cache-name }}-
      - name: Install LLVM
        run: sudo apt install -y llvm-${{ matrix.llvm }} llvm-${{ matrix.llvm }}-dev
      - name: Build docs
        run: >
          cabal haddock
          --enable-documentation
          --haddock-html-location='https://hackage.haskell.org/package/$pkg-$version/docs'
          --haddock-hyperlink-source
          --haddock-options=--quickjump
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs
          publish_dir: ./dist-newstyle/build/x86_64-linux/ghc-${{ matrix.ghc }}/mini-ml-0.1.0.0/doc/html/mini-ml
