name: docs

on:
  push:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Update packages list
        run: cabal update
      - name: Build docs
        run: cabal build
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Publish library docs to the Github Pages"
        run: ./gradlew mkdocsPublish --info

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
